import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import request from 'supertest';
import { createApp } from '../src/app.js';
import { openDatabase } from '../src/db/client.js';
import { SqliteClassificationLog } from '../src/repositories/sqliteClassificationLog.js';
import { SqliteTicketRepository } from '../src/repositories/sqliteTicketRepository.js';
import { TicketService } from '../src/services/ticketService.js';

/** A minimal valid create request; tests override one field at a time. */
export const validTicket = (overrides: Record<string, unknown> = {}) => ({
  customer_id: 'CUST-001',
  customer_email: 'jane.doe@example.com',
  customer_name: 'Jane Doe',
  subject: 'Cannot log in after password reset',
  description: 'I reset my password yesterday and now the login page says my credentials are invalid.',
  ...overrides,
});

/** A clock the test can move forward, so timestamps are predictable. */
export function fakeClock(start = '2026-01-01T10:00:00.000Z') {
  let current = new Date(start).getTime();
  return {
    now: () => new Date(current),
    advance: (ms: number) => {
      current += ms;
    },
  };
}

/**
 * A fresh app on its own empty SQLite database in memory, wired exactly like index.ts.
 * API tests therefore exercise the real SQL queries, but each test starts from a clean slate.
 */
export function createTestApp(options: { now?: () => Date } = {}) {
  const { db } = openDatabase(':memory:');
  const service = new TicketService(new SqliteTicketRepository(db), {
    ...options,
    classificationLog: new SqliteClassificationLog(db),
  });
  return { app: createApp({ ticketService: service }), service, db };
}

/** Uploads `content` to POST /tickets/import as a multipart file. */
export function uploadFile(app: ReturnType<typeof createApp>, content: string, filename: string, query = '') {
  return request(app).post(`/tickets/import${query}`).attach('file', Buffer.from(content, 'utf8'), filename);
}

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), 'fixtures');

/** Reads a file from tests/fixtures (generated by `npm run generate:fixtures`). */
export function readFixture(name: string): string {
  return readFileSync(join(FIXTURES_DIR, name), 'utf8');
}

/** Uploads a fixture file to POST /tickets/import under its own name. */
export function uploadFixture(app: ReturnType<typeof createApp>, name: string, query = '') {
  return uploadFile(app, readFixture(name), name, query);
}

/** The field names that failed, per failed record, from an import summary. */
export function failedFields(summary: { failures: { errors: { field: string }[] }[] }) {
  return summary.failures.map((failure) => failure.errors.map((error) => error.field).sort());
}
